openapi: 3.0.3
info:
  title: Ecomm project API
  description: API desenvolvida para documentar o projeto Ecomm, durante o treinamento sobre HTTP e Swagger da Alura e PagoNxt
  version: 0.1.0
  termsOfService: https://developers.google.com/mobile/terms?hl=pt-br
  contact:
    name: Marcelle Marichal da Rosa
    email: marcelle.rosa@pagonxt.com
  license:
    name: Licença GPLv3
    url: https://www.gnu.org/licenses/quick-guide-gplv3.pt-br.html
externalDocs:
  description: Documentação
  url: https://github.com/marcellemarichal
components:
  schemas:
    pedido:
      type: object
      properties:
        idCliente:
          type: integer
        logradouro:
          type: string
        numero: 
          type: string
        complemento:
          type: string
        cep:
          type: string
        cidade:
          type: string
        uf:
          type: string
        pedidos:
          type: object
          properties:
            idProduto:
              type: integer
            quantidade:
              type: integer
            valorDesconto:
              type: number
            valorTotalProduto:
              type: number
paths:
  /api/orders/{id}:
    parameters: 
      - name: id
        in: path
        schema: 
          type: integer
        required: true
    get:
      tags:
      - Pedidos
      summary: Detalhamento de pedidos pelo ID
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                  type: array
                  items:
                    $ref: "#/components/schemas/pedido"
        404:
          description: Pedido não encontrado
          content:
            application/json:
              example: "Not Found"
  /api/orders:
    post:
      tags:
      - Pedidos
      summary: Realização de um novo pedido
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                email: 
                  type: string
                senha:
                  type: string
                cpf:
                  type: string
                telefone:
                  type: string
                logradouro:
                  type: string
                numero:
                  type: string
                complemento:
                  type: string
                cep:
                  type: string
                cidade:
                  type: string
                UF:
                  type: string
      responses:
        201:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/pedido"
        400:
          description: Solicitação corrompida, confira os dados informados e tente novamente
          content:
            application/json:
              example: Bad request