version: "3.9"
services:
  mysql:
    image: mysql
    volumes:
      - db-mysql-ecomm:/var/lib/mysql
    container_name: mysql-ecomm
    restart: always
    ports:
      - 3307:3307
    environment:
      MYSQL_ROOT_PASSWORD: secret
  product:
    build: ./product
    container_name: ecomm-product
    volumes:
      - product-vol:/node-app/product
    ports:
      - "3003:3003"
  account:
    build: ./account
    container_name: ecomm-account
    volumes:
      - account-vol:/node-app/account
    ports:
      - "3001:3001"
  finance:
    build: ./finance
    container_name: ecomm-finance
    volumes:
      - finance-vol:/node-app/finance
    depends_on:
      - mysql
    ports:
     - 3005:3005
  order:
    build: ./order
    container_name: ecomm-order
    volumes:
      - order-vol:/node-app/order
    ports:
     - 3004:3004
    
volumes:
  db-mysql-ecomm:
  product-vol:
  account-vol:
  finance-vol:
  order-vol: