version: "3.9"
services:
  mongo:
    image: mongo
    container_name: mongo-ecomm
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - "27017:27017"
    security_opt:
      - seccomp:unconfined
  product:
    build: ./product
    container_name: ecomm-product
    depends_on: 
      - mongo
    ports:
      - "3003:3003"
  account:
    build: ./account
    container_name: ecomm-account
    depends_on: 
      - mongo
    ports:
      - "3001:3001"